<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
          <title>Leslie and Christopher</title>


        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('_zf/public/js/bootstrap.min.js'))
            ->prependFile($this->basePath('_zf/public/js/jquery.min.js'))
            ->prependFile($this->basePath('_zf/public/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('_zf/public/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
            <?php echo $this->content; ?>
    </body>
</html>
